# Generated by Django 3.2.13 on 2022-06-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20220609_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='head_image',
            field=models.ImageField(blank=True, upload_to='diary/images/%Y/%m/%d/'),
        ),
    ]
