# Generated by Django 3.2.13 on 2022-06-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hook_msg',
            field=models.TextField(blank=True),
        ),
    ]
